/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CategoriesSkeleton: typeof import('./src/components/feedbacke/CategoriesSkeleton.vue')['default']
    CoffeeMarquee: typeof import('./src/components/ui/CoffeeMarquee.vue')['default']
    ErrorMessage: typeof import('./src/components/ui/product/ErrorMessage.vue')['default']
    Footer: typeof import('./src/components/common/Footer.vue')['default']
    Hero: typeof import('./src/components/common/Hero.vue')['default']
    LoadingSpinner: typeof import('./src/components/feedbacke/LoadingSpinner.vue')['default']
    Navbar: typeof import('./src/components/common/Navbar.vue')['default']
    OurProducts: typeof import('./src/components/ui/OurProducts.vue')['default']
    ProductActionButtons: typeof import('./src/components/ui/product/ProductActionButtons.vue')['default']
    ProductAdditionalInfo: typeof import('./src/components/ui/product/ProductAdditionalInfo.vue')['default']
    ProductBreadcrumb: typeof import('./src/components/ui/product/ProductBreadcrumb.vue')['default']
    ProductCard: typeof import('./src/components/ui/ProductCard.vue')['default']
    ProductDetailsGrid: typeof import('./src/components/ui/product/ProductDetailsGrid.vue')['default']
    ProductImageGallery: typeof import('./src/components/ui/product/ProductImageGallery.vue')['default']
    ProductInfo: typeof import('./src/components/ui/product/ProductInfo.vue')['default']
    ProductReviews: typeof import('./src/components/ui/product/ProductReviews.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/ui/SvgIcon.vue')['default']
    SwiperWrapper: typeof import('./src/components/ui/SwiperWrapper.vue')['default']
    Wecome: typeof import('./src/components/ui/Wecome.vue')['default']
  }
}
