import { createApp } from "vue";
import App from "@/App.vue";
import "@/assets/css/style.css";
import router from "@/router/index";
import Vue3Marquee from "vue3-marquee";
import "virtual:svg-icons-register";
import i18n from "@/plugins/i18n";
import { MotionPlugin } from "@vueuse/motion";
const app = createApp(App);
app.use(MotionPlugin);
app.use(router);
app.use(Vue3Marquee);
app.use(i18n);
app.mount("#app");
